/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "atv.h"
#include <stdlib.h> 
#include <string.h> 

int arg1 = 0;
int arg2 = 0;
void
mathop_1(char *host, char *argv[])
{
	CLIENT *clnt;
	int  *result_1;
	operands  soma_1_arg;
	int  *result_2;
	operands  subtracao_1_arg;
	int  *result_3;
	operands  multiplicacao_1_arg;
	float  *result_4;
	operands  divisao_1_arg;
	int  *result_5;
	operands  modulo_1_arg;
	int  *result_6;
	operands  maior_1_arg;
	int  *result_7;
	operands  menor_1_arg;
	arg1 = atoi(argv[3]);
	arg2 = atoi(argv[4]);

#ifndef	DEBUG
	clnt = clnt_create (host, MATHOP, MATHOP_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if (strcmp(argv[2], "-soma") == 0) {
		soma_1_arg.x = arg1;
		soma_1_arg.y = arg2;
		result_1 = soma_1(&soma_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %d\n", result_1[0]);
		}
	}

	else if (strcmp(argv[2], "-sub") == 0) {
		subtracao_1_arg.x = arg1;
		subtracao_1_arg.y = arg2;
		result_2 = subtracao_1(&subtracao_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %d\n", result_2[0]);
		}
	}

	else if (strcmp(argv[2], "-mult") == 0) {
		multiplicacao_1_arg.x = arg1;
		multiplicacao_1_arg.y = arg2;
		result_3 = multiplicacao_1(&multiplicacao_1_arg, clnt);
		if (result_3 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %d\n", result_3[0]);
		}
	}

	else if (strcmp(argv[2], "-div") == 0) {
		divisao_1_arg.x = arg1;
		divisao_1_arg.y = arg2;
		result_4 = divisao_1(&divisao_1_arg, clnt);
		if (result_4 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %f\n", result_4[0]);
		}
	}

	else if (strcmp(argv[2], "-mod") == 0) {
		modulo_1_arg.x = arg1;
		modulo_1_arg.y = arg2;
		result_5 = modulo_1(&modulo_1_arg, clnt);
		if (result_5 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %d\n", result_5[0]);
		}
	}

	else if (strcmp(argv[2], "-max") == 0) {
		maior_1_arg.x = arg1;
		maior_1_arg.y = arg2;
		result_6 = maior_1(&maior_1_arg, clnt);
		if (result_6 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %d\n", result_6[0]);
		}
	}

	else if (strcmp(argv[2], "-min") == 0) {
		menor_1_arg.x = arg1;
		menor_1_arg.y = arg2;
		result_7 = menor_1(&menor_1_arg, clnt);
		if (result_7 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("Resultado: %d\n", result_7[0]);
		}
	} 

	else {
		printf("Operacao invalida\n");
		exit(1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	mathop_1 (host, argv);
exit (0);
}
