/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "atv.h"
int *
soma_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	result = argp->x + argp->y;

	return &result;
}

int *
subtracao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	result = argp->x - argp->y;

	return &result;
}

int *
multiplicacao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	result = argp->x * argp->y;

	return &result;
}

float *
divisao_1_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	result = ((float)argp->x / argp->y);

	return &result;
}

int *
modulo_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	result = argp->x % argp->y;

	return &result;
}

int *
maior_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	if (argp->x > argp->y) {
		result = argp->x;
	} else {
		result = argp->y;
	}

	return &result;
}

int *
menor_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("O valores sao: %d e %d\n", argp->x, argp->y);
	if (argp->x < argp->y) {
		result = argp->x;
	} else {
		result = argp->y;
	}

	return &result;
}
